# This file was generated by CliMate. Do not edit this file directly or your
# changes may be lost.
#
# Regenerate the files with the same command:
#
#   mix cli.embed --no-moduledoc MixVersion.CLI lib/mix_version/cli -fy
#
defmodule MixVersion.CLI.Argument do
  alias MixVersion.CLI.OptsValidator

  @moduledoc false
  @enforce_keys [:key, :required, :cast, :doc, :type, :repeat]
  defstruct @enforce_keys

  @type vtype :: :integer | :float | :string
  @type caster :: (term -> {:ok, term} | {:error, term}) | {module, atom, [term]}
  @type t :: %__MODULE__{
          key: atom,
          required: boolean,
          type: vtype,
          doc: binary | nil,
          cast: nil | caster
        }

  @doc """
  Builds an argument struct from its key and settings.

  The accepted settings are listed in the module documentation. Raises an
  `ArgumentError` when the settings are invalid.

  ### Examples

  Settings that are not provided are given default values:

      iex> CliMate.CLI.Argument.new(:lang, [])
      %CliMate.CLI.Argument{key: :lang, required: true, cast: nil, doc: "", type: :string, repeat: false}
  """
  def new(key, conf) when is_atom(key) do
    settings = OptsValidator.validate!(conf, "argument #{inspect(key)}", &validate_setting/2)

    %__MODULE__{
      key: key,
      required: Map.get(settings, :required, true),
      cast: Map.get(settings, :cast),
      doc: Map.get(settings, :doc) || "",
      type: Map.get(settings, :type, :string),
      repeat: Map.get(settings, :repeat, false)
    }
  end

  def new(key, _conf) do
    raise ArgumentError, "invalid argument key, expected an atom, got: #{inspect(key)}"
  end

  defp validate_setting(:required, value), do: OptsValidator.boolean(value)

  defp validate_setting(:type, value),
    do: OptsValidator.one_of(value, [:string, :integer, :float])

  defp validate_setting(:doc, value), do: OptsValidator.optional_string(value)
  defp validate_setting(:cast, value), do: OptsValidator.caster(value)
  defp validate_setting(:repeat, value), do: OptsValidator.boolean(value)
  defp validate_setting(_, _), do: :unknown
end
