# This file was generated by CliMate. Do not edit this file directly or your
# changes may be lost.
#
# Regenerate the files with the same command:
#
#   mix cli.embed --no-moduledoc MixVersion.CLI lib/mix_version/cli -fy
#
defmodule MixVersion.CLI.OptsValidator do
  @moduledoc false

  @type result :: {:ok, term} | {:error, String.t()} | :unknown
  @type validator :: (atom, term -> result)

  @spec validate!(term, String.t(), validator) :: map
  def validate!(opts, subject, fun) when is_binary(subject) and is_function(fun, 2) do
    if not Keyword.keyword?(opts) do
      raise ArgumentError,
            "invalid #{subject}, expected a keyword list, got: #{inspect(opts)}"
    end

    Enum.reduce(opts, %{}, fn {key, value}, acc ->
      if Map.has_key?(acc, key) do
        raise ArgumentError, "duplicate setting #{inspect(key)} in #{subject}"
      end

      case fun.(key, value) do
        {:ok, value} ->
          Map.put(acc, key, value)

        {:error, expected} ->
          raise ArgumentError,
                "invalid value for #{inspect(key)} in #{subject}, " <>
                  "expected #{expected}, got: #{inspect(value)}"

        :unknown ->
          raise ArgumentError, "unknown setting #{inspect(key)} in #{subject}"
      end
    end)
  end

  @spec duplicate_keys!(keyword, String.t(), String.t()) :: :ok
  def duplicate_keys!(list, kind, subject) do
    keys = Keyword.keys(list)

    case keys -- Enum.uniq(keys) do
      [] -> :ok
      [dup | _] -> raise ArgumentError, "duplicate #{kind} #{inspect(dup)} in #{subject}"
    end
  end

  def boolean(value) when is_boolean(value), do: {:ok, value}
  def boolean(_), do: {:error, "a boolean"}

  def string(value) when is_binary(value), do: {:ok, value}
  def string(_), do: {:error, "a string"}

  def optional_string(value) when is_binary(value) when is_nil(value), do: {:ok, value}
  def optional_string(_), do: {:error, "a string or nil"}

  def keyword_list(value) do
    if Keyword.keyword?(value),
      do: {:ok, value},
      else: {:error, "a keyword list"}
  end

  def one_of(value, allowed) do
    if value in allowed,
      do: {:ok, value},
      else: {:error, "one of #{Enum.map_join(allowed, ", ", &inspect/1)}"}
  end

  def caster(value) do
    case value do
      nil ->
        {:ok, value}

      f when is_function(f, 1) ->
        {:ok, value}

      {m, f, a} when is_atom(m) and is_atom(f) and is_list(a) ->
        {:ok, value}

      _ ->
        {:error,
         "a valid cast function (a function of arity 1 or a {module, function, args} tuple)"}
    end
  end
end
